exports.userSchema = [
  {
    id: 1,
    name: "Atharva Malve",
    email: "atharva@dev.com",
    occupation: "Software Engineer",
    about_me: "I am a passionate Web Developer.",
    gender: "Male",
    phone: 1234567891,
    age: 25,
    location: "Pune, India",
    skills: ["JavaScript", "React", "Node.js"],
    profile_image_url: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Priya Sharma",
    email: "priya@dev.com",
    occupation: "UI/UX Designer",
    about_me: "Design enthusiast and creative thinker.",
    gender: "Female",
    phone: 9876543210,
    age: 27,
    location: "Bangalore, India",
    skills: ["Figma", "Sketch", "Adobe XD"],
    profile_image_url: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Rohan Patil",
    email: "rohan@dev.com",
    occupation: "Data Scientist",
    about_me: "Love working with data and solving problems.",
    gender: "Male",
    phone: 9988776655,
    age: 30,
    location: "Mumbai, India",
    skills: ["Python", "TensorFlow", "Pandas"],
    profile_image_url: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Sneha Kapoor",
    email: "sneha@dev.com",
    occupation: "Frontend Developer",
    about_me: "Frontend developer who enjoys creating interactive UIs.",
    gender: "Female",
    phone: 9090909090,
    age: 23,
    location: "Delhi, India",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    profile_image_url: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    name: "Arjun Mehta",
    email: "arjun@dev.com",
    occupation: "DevOps Engineer",
    about_me: "Automation is life.",
    gender: "Male",
    phone: 9123456780,
    age: 29,
    location: "Hyderabad, India",
    skills: ["Docker", "Kubernetes", "AWS"],
    profile_image_url: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Tanvi Desai",
    email: "tanvi@dev.com",
    occupation: "Full Stack Developer",
    about_me: "Full stack enthusiast who loves to code.",
    gender: "Female",
    phone: 9988998899,
    age: 26,
    location: "Ahmedabad, India",
    skills: ["React", "Node.js", "MongoDB"],
    profile_image_url: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    name: "Aman Joshi",
    email: "aman@dev.com",
    occupation: "Mobile App Developer",
    about_me: "Building apps that people love.",
    gender: "Male",
    phone: 9876123456,
    age: 28,
    location: "Chennai, India",
    skills: ["Flutter", "Dart", "Firebase"],
    profile_image_url: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    name: "Neha Rane",
    email: "neha@dev.com",
    occupation: "Product Manager",
    about_me: "Bridging tech and business.",
    gender: "Female",
    phone: 9321123456,
    age: 31,
    location: "Pune, India",
    skills: ["Agile", "Scrum", "Product Strategy"],
    profile_image_url: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    name: "Karan Verma",
    email: "karan@dev.com",
    occupation: "Backend Developer",
    about_me: "Love writing scalable backend systems.",
    gender: "Male",
    phone: 8899001122,
    age: 24,
    location: "Kolkata, India",
    skills: ["Node.js", "Express", "PostgreSQL"],
    profile_image_url: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    name: "Ritika Nair",
    email: "ritika@dev.com",
    occupation: "QA Engineer",
    about_me: "Ensuring quality one test at a time.",
    gender: "Female",
    phone: 9345098761,
    age: 27,
    location: "Jaipur, India",
    skills: ["Selenium", "Cypress", "Jest"],
    profile_image_url: "https://randomuser.me/api/portraits/women/10.jpg",
  },
];
